### ISSUE TITLE
'you must use valid amount' even though the amount is valid

### ISSUE THREAD

**Issue by tricdc** [just-an-dev/sodogetip#1]
after leaving the following comments

> +/u/sodogetiptest ;} doge
> +/u/sodogetiptest ;

I now get 'you must use valid amount' after valid comments such as:

> +/u/sodogetiptest 1 doge
> +/u/sodogetiptest 10 doge
> +/u/sodogetiptest 100 doge

address: nfM8qc8iubDTgeGqBfMhnSsguCfjRYfjr1

edit: actually i think the bot was broken before this

**Comment by peoplma** [comment]
Thanks for finding this, I think #2 should fix this

**Comment by just-an-dev** [comment]
Yeah this seems to fix, good job
