### ISSUE TITLE
balance not stable, is this due to testing phase?

### ISSUE THREAD

**Issue by maerco** [just-an-dev/sodogetip#10]
I notice that my balance is changeing without performing any tip
is this because it's a test environment?
or there is some bug?

```
re: +balance
inviato 1 giorno fa da sodogetiptest
Your balance : 2000.00000000
```

this has been reset to zero without any activity

then I was tipped and i request the balance again

```
da talman_au via /r/dogecoin inviato il 11 ore fa
mostra il post a cui è riferito
+/u/sodogetiptest 98 doge
```

```
re: +balance
inviato 11 ore fa da sodogetiptest
Your balance : 98
```

it show correctly the 98 doges

than I used the faucet getting 2000 doges

running again balance

```
re: +balance
inviato 11 ore fa da sodogetiptest
Your balance : 2000
```

It lost 98 doge previously tipped

**Comment by jeje-50** [comment]
yeah it's due to tests

**Comment by just-an-dev** [comment]
yeah
