### ISSUE TITLE
Add a +help command to the footer of each message

### ISSUE THREAD

**Issue by Jasdoge** [just-an-dev/sodogetip#18]
I suggest that the bottom of each message received from the tipbot should include a small help link which requests a help message from the bot.

The primary purpose of the help page would be to list the most useful features of the bot. Such as:

* A list of links to common tasks like withdraw & history
* Your current balance
* Your deposit address
* A link to the full documentation page on the tipbot

**Comment by PowerLemons** [comment]
https://github.com/just-an-dev/sodogetip/pull/22

IMO it would make sense to have the table in both +info and +help. But +help would have a getting started guide with the contents of +info under it.
