### ISSUE TITLE
+info and +balance as the same message?

### ISSUE THREAD

**Issue by PowerLemons** [just-an-dev/sodogetip#23]
This is the message for +info with https://github.com/just-an-dev/sodogetip/pull/22

Here are your account details %s!

^very ^info |&nbsp;
---|---
^Your ^Balance|%s DOGE
^Deposit ^Address|%s
^Withdraw | ^[+withdraw](https://www.reddit.com/message/compose?to=sodogetiptest&subject=%2Bwithdraw&message=%2Bwithdraw%20AMOUNT%20doge%20to%20ADDRESS)

%s being whatever is supposed to be replaced and ^ being superscript.

IMO it would make sense to have +info and +balance have this same message, as it shows everything the user needs to know.

**Comment by just-an-dev** [comment]
yeah there are same info on 2 message maybe delete +info (use same function of balance)

Edit : on info we have address

**Comment by PowerLemons** [comment]
+balance is now using +info. https://github.com/just-an-dev/sodogetip/commit/6a92c7a55a6d35720f9f69c10ae8995a1e4901aa

I think +info is better for balances because it has the nice table with the "very info" header :)
