### ISSUE TITLE
balance on replay

### ISSUE THREAD

**Issue by maerco** [just-an-dev/sodogetip#5]
In order to have a balance we have to dm the bot with +balance in subject and object.
First Time it's work properly, then you you just replay +balance on same message, it will not work.
We need instead to open a new dm.

Should be possible to consider also the replay on the same thread?

**Comment by shibe2** [comment]
Other commands should be handled in a similar way. If the subject is not recognized, but the body contains a correct command, that command should be executed.

**Comment by just-an-dev** [comment]
Will be in v3
