### ISSUE TITLE
@user and ADDRESS when tipping

### ISSUE THREAD

**Issue by PowerLemons** [just-an-dev/sodogetip#57]
Implement:

+/u/dogetipbot _@powerlemons_ 100 doge verify (for tipping a user)

+/u/dogetipbot _ADDRESS_ 100 doge verify (for tipping an address)

**Comment by just-an-dev** [comment]
+/u/sodogetip all verify (for tipping all balance)

**Comment by GaryLittlemore** [comment]
+/u/sodogetiptest random250 doge verify (tipping random tip between 1 and 250)

+/u/sodogetiptest random500 doge verify (tipping random tip between 1 and 500)

+/u/sodogetiptest random1000 doge verify (tipping random tip between 1 and 1000)

**Comment by PowerLemons** [comment]
/(\\+\\/u\\/sodogetiptest)\\s?(@?[0-9a-zA-Z]+)?\\s+(\\d+|[0-9a-zA-Z]+)\\s(doge)\\s(verify)?/g

^ Regex to make it possible

**Comment by PowerLemons** [comment]
Has to ignore case (like uppercase and lowercase) to work by the way

**Comment by just-an-dev** [comment]
this feature will be on #61
