### ISSUE TITLE
Overspending balance

### ISSUE THREAD

**Issue by mrmucox** [just-an-dev/sodogetip#7]
I used the faucet to get 2,000 DOGE, then sent 4 tips of 1,999. The bot replied that it tipped, but none of the transactions show up on the chain.

Tip 1: https://www.reddit.com/r/dogecoin/comments/6a8k34/new_tipbot_running_on_testnet_help_us_test_and/dhdvlf1/

Tip 2: https://www.reddit.com/r/dogecoin/comments/6a8k34/new_tipbot_running_on_testnet_help_us_test_and/dhdvsvc/

Tip 3: https://www.reddit.com/r/dogecoin/comments/6a8k34/new_tipbot_running_on_testnet_help_us_test_and/dhdvsym/

Tip 4: https://www.reddit.com/r/dogecoin/comments/6a8k34/new_tipbot_running_on_testnet_help_us_test_and/dhdw0az/

Dogechain showing my transactions: https://chain.so/address/DOGETEST/ndvBrYrYqcqxgUVH3nYL3zSvq6iav9jTZ2

**Comment by peoplma** [comment]
Thanks for the feedback, I think #8 should fix this

**Comment by just-an-dev** [comment]
no transactions have been sent, we need to update bot to check transaction have been send before replied that it tipped
