### ISSUE TITLE
1 Đ tips are possible

### ISSUE THREAD

**Issue by joen** [just-an-dev/sodogetip#70]
As the bot is "on chain", wouldn't this be eaten up by transaction fees?

I think there should be an error message like: "The minimum tip is 2 doge, as transaction fees are deducted from the tip amount"

**Comment by GaryLittlemore** [comment]
It will still tip 1D and also take a mine fee of 1D, so 2D would come out of your wallet. If the minimum was set to 2D then 3D would come out of the wallet because the 3D would include 1D for the mining fee.

**Comment by joen** [comment]
I see.
