### ISSUE TITLE
Wallet Balance indifference

### ISSUE THREAD

**Issue by GaryLittlemore** [just-an-dev/sodogetip#71]
My bot wallet address is: DGYYfxPkr8kuwhmmKJU17eoqoU9Qu2zkRL https://chain.so/a/cnyi8zq

On reddit the +info says:

Here are your account details /u/GaryLittlemore!
very info	 
Your balance	7575 doge $24.7
Your pending balance	0 doge $0.0
Your spendable balance	7575 doge ($24.7)
Deposit address	DGYYfxPkr8kuwhmmKJU17eoqoU9Qu2zkRL

The blockchain says:

Balance	8,075.00000000
Pending	Nothing
Received	346,642.00000000
Transactions	41

The bot balance is 500d less than the blockchain.

**Comment by peoplma** [comment]
You must have 500 doge tipped out to people who haven't yet registered.  That 500 doge will become spendable again 3 days after the tip if they don't register.  If they do register then the transaction will happen on the blockchain at that time, and the bot will post a verification (if you used `verify`).  The "Your pending balance` right now is unconfirmed transactions.  There is no field that says how much doge you have in queue waiting on people to register to get sent.  We should really add that field to avoid confusion.

**Comment by GaryLittlemore** [comment]
I agree, if that's the case and it makes sense the 'Your pending balance 0 doge $0.0' should be 'Your pending balance 500 doge $1.60'

**Comment by GaryLittlemore** [comment]
I've just checked my +history, I've got 39 tips pending, totalling 1948 doge,. So the figures don't stack up.

**Comment by peoplma** [comment]
You're right, I just checked and I think what happens is when you tip someone who isn't registered, it gets added as "pending" to the tip history.  But then when they do register, the history database doesn't get updated with  "successful".  Another thing we will work on.  Thanks

**Comment by just-an-dev** [comment]
yeah i confirm :) 
history update is broken and will be solved for next release :)
You have 500d in pending... and we will make an update to add this info on balance
