### ISSUE TITLE
security enhancement ideas

### ISSUE THREAD

**Issue by joen** [just-an-dev/sodogetip#72]
I always liked the idea of tipping directly to an address, but it comes with a certain risk. If a reddit account is compromised, there are little chances to secure the tipbot balances. But what if some malicious script/code/whatever tricks a user into sending a withdraw command?

There should be some kind of a text captcha asking for an answer to a (maybe simple math) question. This would not secure your funds if your account has been "broken into", but it would prevent automatic attempts. It should be active for all commands that transfer doges out:

- tips to addresses
- tips over 1000 doge
- withdrawals

**Comment by peoplma** [comment]
Reddit uses OAuth, so you would have to give explicit permission for that third party script to access your reddit account.  A bot couldn't do it en masse.  Perhaps if there were a phishing attack on redditors pretending to be coming from reddit or something, but still, reddit doesn't give out user emails.  I guess someone could mass-PM spam users with a link asking for authorization to their reddit account, and some would probably be stupid enough to give it.

Also, the extra hassle of having to do a captcha every time you want to tip or withdraw I think would make people use it less.  Also, putting a cap on 1000 doge where anything over requires a captcha wouldn't solve the problem, as a script with access to your reddit account could just repeatedly tip 999 doge, so to add any extra security it would have to be required for all tips and withdraws.

Instead, our goal for extra security is to provide the option of registration with multisig.  There could be a 2of3 multisig address registration option where the user provides 2 public keys and the bot provides one.  When you go to tip or withdraw, the bot would require you to sign the transaction manually.  The user would own 2 privkeys, so they wouldn't even need the bot to be online to withdraw their balance, and it would be impossible for the bot owners to steal coins.   The downside is the inconvenience of manually signing transactions, but the multisig feature could be enabled/disabled at will by the user, they needn't use it all the time.

There could also be a 1of2 option, where users don't need to sign tips/withdraws manually, and they also don't need the bot to be online to make a withdraw - however the bot owner (or a script with access to your reddit account) can still steal user coins with 1of2.

With these multisig enable/disable options, we hope to let users decide the level of security they want their coins to be stored with.

How does that sound?

**Comment by joen** [comment]
that sounds great!
