### ISSUE TITLE
Buy gold for other users

### ISSUE THREAD

**Issue by Phoenix616** [just-an-dev/sodogetip#93]
Currently it seems like it is only possible to buy gold for yourself. But gold is way more commonly bought for other users so it would be cool if the bot could support that, maybe even gilding a comment via the bot. (not sure if the API supports that) It could even leave a comment there that someone gilded via the bot.

Commands could look like this:
```
subject: +gold
content: buy <username>
```
```
subject: +gold
content: buy <link to comment>
```

**Comment by just-an-dev** [comment]
i will add possibility to buy gold for someone, and i need to look for comment gilding :)

**Comment by yottalogical** [comment]
Alternative syntax:

`+/u/SoDogeTip gold`

You would reply this directly below the comment or post.
